version: '3.9'

services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - python:3.10
        - core:latest
    container_name: core
    image: core
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    command: ["python", "cli.py"]
    env_file:
      - .env
    ports:
      - "${APP_EXTERNAL_PORT:?specify_port}:${APP_INTERNAL_PORT:?specify_port}"

  db:
    image: postgres:14.2
    container_name: core-db
    volumes:
      - core_pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${CORE_DB}

#  migrations:
#    container_name: core_migrations
#    image: core
#    volumes:
#      - .:/opt/app
#    working_dir: /opt/app/core/db
#    command: ["alembic", "upgrade", "head"]
#    env_file:
#      - .env

  datasource_1:
    build:
      context: ./datasource_mock
      dockerfile: Dockerfile
    container_name: datasource_1
    image: datasource
    volumes:
      - ./test_data/:/opt/app/data
    environment:
      - PATH_TO_DATA=/opt/app/data/${DATA_NAME1:-data1.json}
      - DELAY=${DATA_DELAY1:-0}
    working_dir: /opt/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0"]
    env_file:
      - .env
    ports:
      - "${DATA_PORT1:?specify_port}:8000"

  datasource_2:
    build:
      context: ./datasource_mock
      dockerfile: Dockerfile
    container_name: datasource_2
    image: datasource
    volumes:
      - ./test_data/:/opt/app/data
    environment:
      - PATH_TO_DATA=/opt/app/data/${DATA_NAME1:-data2.json}
      - DELAY=${DATA_DELAY2:-0}
    working_dir: /opt/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0"]
    env_file:
      - .env
    ports:
      - "${DATA_PORT2:?specify_port}:8000"

  datasource_3:
    build:
      context: ./datasource_mock
      dockerfile: Dockerfile
    container_name: datasource_3
    image: datasource
    volumes:
      - ./test_data/:/opt/app/data
    environment:
      - PATH_TO_DATA=/opt/app/data/${DATA_NAME1:-data3.json}
      - DELAY=${DATA_DELAY3:-0}
    working_dir: /opt/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0"]
    env_file:
      - .env
    ports:
      - "${DATA_PORT3:?specify_port}:8000"

volumes:
  core_pgdata:
